config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#index'
    resources :categories
    resources :posts
    
    get 'pages/about'
    get 'pages/oboz'
    get 'pages/przydatne'
    get 'pages/kontakt'
    
    get 'pages/gromada'
    get 'pages/dziupla'
    get 'pages/puzzle'
    get 'pages/dysk'
    get 'pages/berserk'
    get 'pages/emilki'
    get 'pages/prezni'
    
    resources :pages do
      post 'load_more_posts', on: :collection
    end
  
  get '/admin', to: "admin#index"
  
  namespace :admin do

    resources :categories
    resources :posts
    
  end
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
    
    has_many :posts
    
    validates :name, presence: true, uniqueness: true
    
end

app/models/post.rb
class Post < ActiveRecord::Base
    
    belongs_to :category
    
    validates :title, presence: true
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    
    before_action :set_category, :only =>[:show, :edit, :destroy, :update]
    
    
    def index
        @categories = Category.all
        respond_to do |format|
            format.html
            format.json {render json: @categories}
        end
    end
    
    
    def show
        respond_to do |format|
           format.html
           format.json { render json: @category }
        end    
    end
    
    
    def new
        @category = Category.new
    end
    
    
    def create
        @category = Category.new(category_params)
        respond_to do |format|
            if @category.save
                format.html {redirect_to admin_categories_path, notice: 'Category created'}
            else
                format.html {render action: 'new', alert: 'Error while creating'}
            end
        end    
    end
    
    
    def edit
    end
    
    
    def update
        respond_to do |format|
            if @category.update{post_params}
                format.html {redirect_to admin_post_path, notice: "Category updated"}
            else
                format.html {render action: 'edit', alert: "Error while editing"}
            end
        end  
    end
    
    
    def destroy 
        if @category.delete
            redirect_to admin_categories_path, notice: "Category Deleted"
        else
            redirect_to admin_categories_path, notice: "Error while deleting"
        end
    end
    
    
    
    protected
    
    def set_category
        @category = Category.find(params[:id])  
    end
    
    
    def category_params
        params.require(:category).permit(:name)
    end
    
    
    
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index 
    @posts = Post.all
  end
  
  def show
  end


  def new
    @post = Post.new
  end
  

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path, notice: "Post created"
    else
      render action: "new"
    end
  end
  

  def edit
  end
  

  def update
    if @post.update_attributes(post_params)
      redirect_to admin_posts_path, notice: "Post updated"
    else
      render action: "edit"
    end
  end
  

  def destroy 
    if @post.delete
      redirect_to admin_posts_path, notice: "Post deleted"
    else
      redirect_to admin_posts_path, notice: "Error while deleting"
    end
  end
  

  protected

  def set_post
    @post = Post.find(params[:id])  
  end

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    
    def index
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    
    def index
        @posts = Post.all.limit(4).order(created_at: :desc)
    end
    
    def show
        respond_to do |format|
           format.html
           format.json
        end    
    end
    
    def load_more_posts
        @posts = Post.where("id < ?", params[:lowest_id]).limit(3).order(created_at: :desc)
        render :layout => false
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :set_post, only: [:show]

    def index
        @posts = Post.all
    end
    
    def show
        respond_to do |format|
           format.html
           format.json
        end    
    end
    
    def set_post
        @post = Post.find(params[:id])  
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/categories/_form.html.haml
= simple_form_for [:admin, @category], :html => {class: "form-horizontal"} do |f|
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.input_field :name, label: false, class: "form-control"
  - if @category.id.present?
    .form-group
      = f.label :slug, class: "col-sm-2 control-label"
      .col-sm-10
        = f.input_field :slug, label: false, class: "form-control"
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.button :submit, "Zapisz" , class: "btn btn-default"

app/views/admin/categories/index.html.haml
- content_for :breadcrumb do
    %li.active Lista Kategorii

= link_to 'Dodaj kategorię', new_admin_category_path

%ul
    - @categories.each do |category|
        %li= category.name

app/views/admin/categories/new.html.haml
- content_for :breadcrumb do
    %li
        = link_to 'Lista Kategorii', admin_categories_path
    %li.active Nowa Kategoria

= render 'form', :url => admin_categories_path(@category)

app/views/admin/index.html.haml
Admin content only

app/views/admin/posts/_form.html.haml
= simple_form_for @post, :url => url, :html => {:class => 'form-horizontal'} do |f|
    .form-group
        =f.label :title, :class => "col-sm-2 control-label"
        .col-sm-10
            = f.input_field :title, :label => false, :class => "form-control"
        =f.label :body, :class => "col-sm-2 control-label"
        .col-sm-10
            = f.input_field :body, :label => false, :class => "form-control"
    .form-group
        .col-sm-offset-2.col-sm-10
            = f.button :submit, :class => "btn btn-success"

app/views/admin/posts/index.html.haml
- content_for :breadcrumb do
  %li.active Lista Postów

%h1= t('admin.posts.all')

= link_to t('admin.posts.new'), new_admin_post_path
%br

%ul
  - @posts.each do |post|
    %li= link_to post.title, admin_post_url(post)

app/views/admin/posts/new.html.haml
- content_for :breadcrumb do
    %li
        = link_to 'Lista Postów', admin_posts_path
    %li.active Nowy Post

= render 'admin/posts/form', :url => admin_posts_path(@post)

app/views/admin/posts/show.html.haml
= link_to "Wszystkie posty", admin_posts_path
%h3= @post.title
%h4= @post.body
= link_to "Usuń post", admin_post_path(@post), :method => :delete

app/views/layouts/_admin_nav.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Admin Panel by Rob
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "#"} Powrót do strony głównej

    / /.navbar-collapse
  / /.container-fluid

app/views/layouts/_admin_side_nav.html.haml
%ul.nav.nav-pills.nav-stacked
    %li.active
        = link_to t('admin.menu.dashboard'), admin_path
    %li
        = link_to t('admin.menu.posts'), admin_posts_path
    %li
        = link_to t('admin.menu.categories'), admin_categories_path
    %li
        %a{ :href=>"#" } Another
    %li
        %a{ :href=>"#" } Another
    %li
        %a{ :href=>"#" } Another

app/views/layouts/_application_nav.html.haml
%nav.navbar.navbar-inverse
  .container  
    .container-fluid
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{:href => '#'} Strona Główna
      / Collect the nav links, forms, and other content for toggling
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li
            %span.sr-only (current)
          %li
            = link_to "Kim jesteśmy?", pages_about_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"} 
              Nasze drużyny
              %span.caret
            %ul.dropdown-menu
              %li
                = link_to "Gromada Zuchowa", pages_gromada_path
              %li.divider{:role => "separator"}
              %li
                = link_to "Dziupla", pages_dziupla_path
              %li
                = link_to "Puzzle", pages_puzzle_path
              %li.divider{:role => "separator"}
              %li
                = link_to "DYSK", pages_dysk_path
              %li
                = link_to "Berserk", pages_berserk_path
              %li.divider{:role => "separator"}
              %li
                = link_to "Emilki", pages_emilki_path
              %li
                = link_to "Prężni", pages_prezni_path
          %li
            = link_to "Zimowisko 2016", pages_oboz_path
          %li
            = link_to "Przydatne", pages_przydatne_path
          %li.active
            = link_to "Kontakt", pages_kontakt_path
      / /.navbar-collapse
    / /.container-fluid

app/views/layouts/_facebook_plugin.html.haml
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));


.fb-page{"data-adapt-container-width" => "true", "data-hide-cover" => "false", "height" => "620px", "data-href" => "https://www.facebook.com/ziel6na", "data-show-facepile" => "true", "data-show-posts" => "true", "data-small-header" => "true"}
  .fb-xfbml-parse-ignore
    %blockquote{:cite => "https://www.facebook.com/ziel6na"}
      %a{:href => "https://www.facebook.com/ziel6na"} Ziel6na
      

app/views/layouts/_footer_nav.html.haml
%nav.navbar.navbar-inverse.custom-footer
    .container
        .navbar-text.pull-left.custom-text
            %p Dzięki za odwiedziny!
        .navbar-text.pull-right
            = image_tag "ror_icon.png", :class => "custom-icon"
            = image_tag "bootstrap_icon.png", :class => "custom-icon"
            = image_tag "html5_icon.png", :class => "custom-icon"
            = image_tag "css3_icon.png", :class => "custom-icon"
            = image_tag "javascript_icon.png", :class => "custom-icon"
            = image_tag "jquery_icon.png", :class => "custom-icon"
        .navbar-text.pull-right.custom-text
            %p © Robert Szczygieł

app/views/layouts/_noty_html.haml
- if notice.present?
  :javascript
    noty({text: "#{notice}", timeout: 3000, layout: 'bottom', type: 'success'});
- if alert.present?
  :javascript
    noty({text: "#{alert}", timeout: 3000, layout: 'bottom', type: 'error'});

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Admin panel
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', media: 'all'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', media: 'all'
    = csrf_meta_tags
  %body
    = render 'layouts/admin_nav'
    .container
      .col-sm-2
        =render 'layouts/admin_side_nav'
      .col-sm-10
        %ol.breadcrumb
          %li
            %a{:href => admin_path} Home
          =yield :breadcrumb

        = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Rails project
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all'
    = stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js', media: 'all'
    = csrf_meta_tags
  %body
    %div.custom-bgbanner
      .container
        = image_tag("banner.jpg", width:"100%")
    = render 'layouts/application_nav'
    %div.custom-main
      .container.custom-bgcontainer
        .col-sm-8.custom-main-top.custom-main-bottom
          = yield
        .col-sm-4.panel.panel-success.custom-main-top
          = render 'layouts/facebook_plugin'
    = render 'layouts/footer_nav'

app/views/pages/about.html.haml
%div.panel.panel-success
    %div.panel-heading
        %h4 O szczepie
    %div.panel-body
        %img{:alt => "Ups, coś poszło nie tak", :src => "http://zielona6.pl/wp-content/uploads/2013/04/30lecieZiel6nej-002.jpg", :style =>"width:100%"}
        %p Szczep Zielona Szóstka z Poznania działa od 1983 roku, na początku funkcjonował jako drużyna przy VII LO im. Dąbrówki, gdzie do tej pory mamy harcówkę. Dzięki dużej tendencji wzrostowej drużyna szybko przekształciła się w szczep, którego członkowie i członkinie noszą zielone chusty i pagony, na głowie chłopacy berety lub rogatywki, a dziewczyny kapelusze.
        
        %p W szczepie działa obecnie 5 drużyn, w których członkami są uczniowie i uczennice szkół podstawowych, gimnazjum i liceum. Jeśli szukasz drużyny dla siebie to wiedz, że:
        
        %ul
            %li Gromada Zuchowa to dziewczyny i chłopacy z klas 1-3
            %li Dziupla to dziewczyny z klas 4-6
            %li Puzzle to chłopacy z klas 4-6
            %li DYSK to dziewczyny z gimnazjum
            %li Berserk to chłopacy z gimnazjum
            %li Emillki to dziewczyny z liceum
            %li Pręzni to chłopacy z liceum
            %li Każda drużyna ma co tydzień zbiórki, jeśli chcesz przyjść na następną zajrzyj do zakładki kontakt.
        
        %p Oprócz zbiórek jeździmy też na biwaki, organizujemy rajdy i zimowiska. Ale najważniejszą i najlepszą rzeczą jest oczywiście OBÓZ! Nasz szczep jeździ na obozy typu puszczańskiego, co oznacza spanie pod namiotem przez  3 tygodnie na samodzielnie wybudowanej pryczy, w pięknym lesie gdzie nie ma prądu, a budzi Cię śpiew ptaków, lub gwizdek oboźnego.
        
        %p Do tej pory udało Nam się zorganizować obozy w takich miejscach – MAPA
        
        %p Ziel6na bo tak zwykliśmy siebie nazywać to szczep działający w Hufcu „Siódemka”, gdzie Nasi instruktorzy i instruktorki cieszą się nieposzlakowaną opinią.
        
        %p Aktualnie funkcję szczepowej pełni pwd. Martyna Rochatka HR, a jej zastępczynią jest pwd. Hanna Kulczak HO.
        
        %p Należałoby także napisać jak wspaniałym Ziel6na jest środowiskiem i jak dobrze bawimy się już od 30 lat, ale w to z pewnością nie uwierzycie dopóki Nas nie poznacie. Dlatego zapraszamy serdecznie, na pewno w tym tygodniu jest jakaś zbiórka lub biwak, a może właśnie wybieramy się na zimowisko?

app/views/pages/gromada.html.haml
%p o gromadzie!

app/views/pages/index.html.haml
%div.posts-list
  - @posts.each do |post|
    %div.post-item.panel.panel-success{data: { id: post.id }}
      %p.panel-heading= post.title
      %p.panel-body= post.body
%button.btn.btn-success.load-more-button{:type => "button"} Load More

app/views/pages/kontakt.html.haml
%div.panel.panel-success
    %div.panel-heading
        %h4 KONTAKT!
    %div.panel-body
        %img{:alt => "Ups, coś poszło nie tak", :src => "http://zielona6.pl/wp-content/uploads/2013/04/30lecieZiel6nej-002.jpg", :style =>"width:100%"}
        %p Szczep Zielona Szóstka z Poznania działa od 1983 roku, na początku funkcjonował jako drużyna przy VII LO im. Dąbrówki, gdzie do tej pory mamy harcówkę. Dzięki dużej tendencji wzrostowej drużyna szybko przekształciła się w szczep, którego członkowie i członkinie noszą zielone chusty i pagony, na głowie chłopacy berety lub rogatywki, a dziewczyny kapelusze.
        
        %p W szczepie działa obecnie 5 drużyn, w których członkami są uczniowie i uczennice szkół podstawowych, gimnazjum i liceum. Jeśli szukasz drużyny dla siebie to wiedz, że:
        
        %ul
            %li Gromada Zuchowa to dziewczyny i chłopacy z klas 1-3
            %li Dziupla to dziewczyny z klas 4-6
            %li Puzzle to chłopacy z klas 4-6
            %li DYSK to dziewczyny z gimnazjum
            %li Berserk to chłopacy z gimnazjum
            %li Emillki to dziewczyny z liceum
            %li Pręzni to chłopacy z liceum
            %li Każda drużyna ma co tydzień zbiórki, jeśli chcesz przyjść na następną zajrzyj do zakładki kontakt.
        
        %p Oprócz zbiórek jeździmy też na biwaki, organizujemy rajdy i zimowiska. Ale najważniejszą i najlepszą rzeczą jest oczywiście OBÓZ! Nasz szczep jeździ na obozy typu puszczańskiego, co oznacza spanie pod namiotem przez  3 tygodnie na samodzielnie wybudowanej pryczy, w pięknym lesie gdzie nie ma prądu, a budzi Cię śpiew ptaków, lub gwizdek oboźnego.
        
        %p Do tej pory udało Nam się zorganizować obozy w takich miejscach – MAPA
        
        %p Ziel6na bo tak zwykliśmy siebie nazywać to szczep działający w Hufcu „Siódemka”, gdzie Nasi instruktorzy i instruktorki cieszą się nieposzlakowaną opinią.
        
        %p Aktualnie funkcję szczepowej pełni pwd. Martyna Rochatka HR, a jej zastępczynią jest pwd. Hanna Kulczak HO.
        
        %p Należałoby także napisać jak wspaniałym Ziel6na jest środowiskiem i jak dobrze bawimy się już od 30 lat, ale w to z pewnością nie uwierzycie dopóki Nas nie poznacie. Dlatego zapraszamy serdecznie, na pewno w tym tygodniu jest jakaś zbiórka lub biwak, a może właśnie wybieramy się na zimowisko?

app/views/pages/load_more_posts.html.haml
- @posts.each do |post|
  %div.post-item.panel.panel-success{data: { id: post.id }}
    %p.panel-heading= post.title
    %p.panel-body= post.body

app/views/pages/oboz.html.haml
%div.panel.panel-success
    %div.panel-heading
        %h4 OBÓZZ!
    %div.panel-body
        %img{:alt => "Ups, coś poszło nie tak", :src => "http://zielona6.pl/wp-content/uploads/2013/04/30lecieZiel6nej-002.jpg", :style =>"width:100%"}
        %p Szczep Zielona Szóstka z Poznania działa od 1983 roku, na początku funkcjonował jako drużyna przy VII LO im. Dąbrówki, gdzie do tej pory mamy harcówkę. Dzięki dużej tendencji wzrostowej drużyna szybko przekształciła się w szczep, którego członkowie i członkinie noszą zielone chusty i pagony, na głowie chłopacy berety lub rogatywki, a dziewczyny kapelusze.
        
        %p W szczepie działa obecnie 5 drużyn, w których członkami są uczniowie i uczennice szkół podstawowych, gimnazjum i liceum. Jeśli szukasz drużyny dla siebie to wiedz, że:
        
        %ul
            %li Gromada Zuchowa to dziewczyny i chłopacy z klas 1-3
            %li Dziupla to dziewczyny z klas 4-6
            %li Puzzle to chłopacy z klas 4-6
            %li DYSK to dziewczyny z gimnazjum
            %li Berserk to chłopacy z gimnazjum
            %li Emillki to dziewczyny z liceum
            %li Pręzni to chłopacy z liceum
            %li Każda drużyna ma co tydzień zbiórki, jeśli chcesz przyjść na następną zajrzyj do zakładki kontakt.
        
        %p Oprócz zbiórek jeździmy też na biwaki, organizujemy rajdy i zimowiska. Ale najważniejszą i najlepszą rzeczą jest oczywiście OBÓZ! Nasz szczep jeździ na obozy typu puszczańskiego, co oznacza spanie pod namiotem przez  3 tygodnie na samodzielnie wybudowanej pryczy, w pięknym lesie gdzie nie ma prądu, a budzi Cię śpiew ptaków, lub gwizdek oboźnego.
        
        %p Do tej pory udało Nam się zorganizować obozy w takich miejscach – MAPA
        
        %p Ziel6na bo tak zwykliśmy siebie nazywać to szczep działający w Hufcu „Siódemka”, gdzie Nasi instruktorzy i instruktorki cieszą się nieposzlakowaną opinią.
        
        %p Aktualnie funkcję szczepowej pełni pwd. Martyna Rochatka HR, a jej zastępczynią jest pwd. Hanna Kulczak HO.
        
        %p Należałoby także napisać jak wspaniałym Ziel6na jest środowiskiem i jak dobrze bawimy się już od 30 lat, ale w to z pewnością nie uwierzycie dopóki Nas nie poznacie. Dlatego zapraszamy serdecznie, na pewno w tym tygodniu jest jakaś zbiórka lub biwak, a może właśnie wybieramy się na zimowisko?

app/views/pages/przydatne.html.haml
%div.panel.panel-success
    %div.panel-heading
        %h4 PRZYDATNE!
    %div.panel-body
        %img{:alt => "Ups, coś poszło nie tak", :src => "http://zielona6.pl/wp-content/uploads/2013/04/30lecieZiel6nej-002.jpg", :style =>"width:100%"}
        %p Szczep Zielona Szóstka z Poznania działa od 1983 roku, na początku funkcjonował jako drużyna przy VII LO im. Dąbrówki, gdzie do tej pory mamy harcówkę. Dzięki dużej tendencji wzrostowej drużyna szybko przekształciła się w szczep, którego członkowie i członkinie noszą zielone chusty i pagony, na głowie chłopacy berety lub rogatywki, a dziewczyny kapelusze.
        
        %p W szczepie działa obecnie 5 drużyn, w których członkami są uczniowie i uczennice szkół podstawowych, gimnazjum i liceum. Jeśli szukasz drużyny dla siebie to wiedz, że:
        
        %ul
            %li Gromada Zuchowa to dziewczyny i chłopacy z klas 1-3
            %li Dziupla to dziewczyny z klas 4-6
            %li Puzzle to chłopacy z klas 4-6
            %li DYSK to dziewczyny z gimnazjum
            %li Berserk to chłopacy z gimnazjum
            %li Emillki to dziewczyny z liceum
            %li Pręzni to chłopacy z liceum
            %li Każda drużyna ma co tydzień zbiórki, jeśli chcesz przyjść na następną zajrzyj do zakładki kontakt.
        
        %p Oprócz zbiórek jeździmy też na biwaki, organizujemy rajdy i zimowiska. Ale najważniejszą i najlepszą rzeczą jest oczywiście OBÓZ! Nasz szczep jeździ na obozy typu puszczańskiego, co oznacza spanie pod namiotem przez  3 tygodnie na samodzielnie wybudowanej pryczy, w pięknym lesie gdzie nie ma prądu, a budzi Cię śpiew ptaków, lub gwizdek oboźnego.
        
        %p Do tej pory udało Nam się zorganizować obozy w takich miejscach – MAPA
        
        %p Ziel6na bo tak zwykliśmy siebie nazywać to szczep działający w Hufcu „Siódemka”, gdzie Nasi instruktorzy i instruktorki cieszą się nieposzlakowaną opinią.
        
        %p Aktualnie funkcję szczepowej pełni pwd. Martyna Rochatka HR, a jej zastępczynią jest pwd. Hanna Kulczak HO.
        
        %p Należałoby także napisać jak wspaniałym Ziel6na jest środowiskiem i jak dobrze bawimy się już od 30 lat, ale w to z pewnością nie uwierzycie dopóki Nas nie poznacie. Dlatego zapraszamy serdecznie, na pewno w tym tygodniu jest jakaś zbiórka lub biwak, a może właśnie wybieramy się na zimowisko?

app/views/posts/index.html.haml
%h1 Lista postów
%ul
  - @posts.each do |post|
    %li= link_to post.title, post_url(post)

app/views/posts/show.html.haml
= link_to "Wszystkie posty", posts_path
%h3= @post.title
%h4= @post.body